---
apiVersion: v1
kind: Namespace
metadata:
  name: trading-system
  labels:
    name: trading-system
    environment: development
---
#apiVersion: v1
#kind: Namespace
#metadata:
  #name: monitoring
  #labels:
    #name: monitoring
    #environment: development
#---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    name: databases
    environment: development
